[package]
name = "igloo-connector-filesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
igloo-common = { path = "../../common" }
tokio = { version = "1", features = ["full"] }
tonic = "0.13"
prost = "0.14"
prost-types = "0.14"
