repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: cargo fmt
        entry: bash -c 'cargo fmt --all && git add .'  # auto-stage changes
        language: system
        types: [rust]
        pass_filenames: false

      - id: clippy
        name: cargo clippy
        entry: bash -c 'cargo clippy --workspace --all-targets -- -D warnings && git add .'  # auto-stage changes
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-build
        name: cargo build
        entry: cargo build --workspace --all-targets
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        entry: cargo test --workspace --all-targets
        language: system
        types: [rust]
        pass_filenames: false