[package]
name = "igloo-coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
igloo-api = { path = "../api" }
igloo-common = { path = "../common" }
igloo-engine = { path = "../engine" }
tokio = { version = "1", features = ["full"] }
tonic = "0.13"
prost = "0.14"
prost-types = "0.14"
chrono = "0.4"
