[package]
name = "igloo-common"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.13"
prost = "0.14"
prost-types = "0.14"
thiserror = "2.0"
sqlparser = "0.56.0"
